import socket
import struct

# Address family constants
# Address family constants
AF_UNSPEC = getattr(socket, 'AF_UNSPEC', 0)
AF_INET = getattr(socket, 'AF_INET', 2)
AF_NETLINK = getattr(socket, 'AF_NETLINK', 16)
AF_BRIDGE = getattr(socket, 'AF_BRIDGE', 7)

AF_UNIX = getattr(socket, 'AF_UNIX', 1)
AF_LOCAL = getattr(socket, 'AF_LOCAL', 1)
AF_AX25 = 3
AF_IPX = 4
AF_APPLETALK = 5
AF_NETROM = 6
AF_ATMPVC = 8
AF_X25 = 9
AF_INET6 = getattr(socket, 'AF_INET6', 10)
AF_ROSE = 11
AF_DECNET = 12
AF_NETBEUI = 13
AF_SECURITY = 14
AF_KEY = 15
AF_PACKET = 17
AF_ASH = 18
AF_ECONET = 19
AF_ATMSVC = 20
AF_RDS = 21
AF_SNA = 22
AF_IRDA = 23
AF_PPPOX = 24
AF_WANPIPE = 25
AF_LLC = 26
AF_IB = 27
AF_MPLS = 28
AF_CAN = 29
AF_TIPC = 30
AF_BLUETOOTH = 31
AF_IUCV = 32
AF_RXRPC = 33
AF_ISDN = 34
AF_PHONET = 35
AF_IEEE802154 = 36
AF_CAIF = 37
AF_ALG = 38
AF_NFC = 39
AF_VSOCK = 40
AF_KCM = 41
AF_QIPCRTR = 42
AF_SMC = 43
AF_XDP = 44
AF_MCTP = 45

AF_MAX = 46

# Protocol family constants (aliases for address families)
PF_UNSPEC = AF_UNSPEC
PF_UNIX = AF_UNIX
PF_LOCAL = AF_LOCAL
PF_INET = AF_INET
PF_AX25 = AF_AX25
PF_IPX = AF_IPX
PF_APPLETALK = AF_APPLETALK
PF_NETROM = AF_NETROM
PF_BRIDGE = AF_BRIDGE
PF_ATMPVC = AF_ATMPVC
PF_X25 = AF_X25
PF_INET6 = AF_INET6
PF_ROSE = AF_ROSE
PF_DECNET = AF_DECNET
PF_NETBEUI = AF_NETBEUI
PF_SECURITY = AF_SECURITY
PF_KEY = AF_KEY
PF_NETLINK = AF_NETLINK
PF_ROUTE = PF_NETLINK  # Alias
PF_PACKET = AF_PACKET
PF_ASH = AF_ASH
PF_ECONET = AF_ECONET
PF_ATMSVC = AF_ATMSVC
PF_RDS = AF_RDS
PF_SNA = AF_SNA
PF_IRDA = AF_IRDA
PF_PPPOX = AF_PPPOX
PF_WANPIPE = AF_WANPIPE
PF_LLC = AF_LLC
PF_IB = AF_IB
PF_MPLS = AF_MPLS
PF_CAN = AF_CAN
PF_TIPC = AF_TIPC
PF_BLUETOOTH = AF_BLUETOOTH
PF_IUCV = AF_IUCV
PF_RXRPC = AF_RXRPC
PF_ISDN = AF_ISDN
PF_PHONET = AF_PHONET
PF_IEEE802154 = AF_IEEE802154
PF_CAIF = AF_CAIF
PF_ALG = AF_ALG
PF_NFC = AF_NFC
PF_VSOCK = AF_VSOCK
PF_KCM = AF_KCM
PF_QIPCRTR = AF_QIPCRTR
PF_SMC = AF_SMC
PF_XDP = AF_XDP
PF_MCTP = AF_MCTP

PF_MAX = AF_MAX

# Interface Flags
IFF_LOWER_UP = 0x10000
IFF_DORMANT = 0x20000

# IFLA_* top-level attributes
IFLA_UNSPEC = 0
IFLA_ADDRESS = 1
IFLA_BROADCAST = 2
IFLA_IFNAME = 3
IFLA_MTU = 4
IFLA_LINK = 5
IFLA_QDISC = 6
IFLA_STATS = 7
IFLA_COST = 8
IFLA_PRIORITY = 9
IFLA_MASTER = 10
IFLA_WIRELESS = 11
IFLA_PROTINFO = 12
IFLA_TXQLEN = 13
IFLA_MAP = 14
IFLA_WEIGHT = 15
IFLA_OPERSTATE = 16
IFLA_LINKMODE = 17
IFLA_LINKINFO = 18
IFLA_NET_NS_PID = 19
IFLA_IFALIAS = 20
IFLA_NUM_VF = 21
IFLA_VFINFO_LIST = 22
IFLA_STATS64 = 23
IFLA_VF_PORTS = 24
IFLA_PORT_SELF = 25
IFLA_AF_SPEC = 26
IFLA_GROUP = 27
IFLA_NET_NS_FD = 28
IFLA_EXT_MASK = 29
IFLA_PROMISCUITY = 30
IFLA_NUM_TX_QUEUES = 31
IFLA_NUM_RX_QUEUES = 32
IFLA_CARRIER = 33
IFLA_PHYS_PORT_ID = 34
IFLA_CARRIER_CHANGES = 35
IFLA_PHYS_SWITCH_ID = 36
IFLA_LINK_NETNSID = 37
IFLA_PHYS_PORT_NAME = 38
IFLA_PROTO_DOWN = 39
IFLA_GSO_MAX_SEGS = 40
IFLA_GSO_MAX_SIZE = 41
IFLA_PAD = 42
IFLA_XDP = 43
IFLA_EVENT = 44
IFLA_NEW_NETNSID = 45
IFLA_IF_NETNSID = 46
IFLA_CARRIER_UP_COUNT = 47
IFLA_CARRIER_DOWN_COUNT = 48
IFLA_NEW_IFINDEX = 49
IFLA_MIN_MTU = 50
IFLA_MAX_MTU = 51
IFLA_PROP_LIST = 52
IFLA_ALT_IFNAME = 53
IFLA_PERM_ADDRESS = 54
IFLA_PROTO_DOWN_REASON = 55
IFLA_MAX = 55

# IF_OPER_* states
IF_OPER_UNKNOWN = 0
IF_OPER_NOTPRESENT = 1
IF_OPER_DOWN = 2
IF_OPER_LOWERLAYERDOWN = 3
IF_OPER_TESTING = 4
IF_OPER_DORMANT = 5
IF_OPER_UP = 6

# Link XSTATS types
LINK_XSTATS_TYPE_UNSPEC = 0
LINK_XSTATS_TYPE_BRIDGE = 1
LINK_XSTATS_TYPE_BOND = 2
LINK_XSTATS_TYPE_MAX = 2

# XDP attachment states
XDP_ATTACHED_NONE = 0
XDP_ATTACHED_DRV = 1
XDP_ATTACHED_SKB = 2
XDP_ATTACHED_HW = 3
XDP_ATTACHED_MULTI = 4

# XDP Flags
XDP_FLAGS_UPDATE_IF_NOEXIST = 1 << 0
XDP_FLAGS_SKB_MODE = 1 << 1
XDP_FLAGS_DRV_MODE = 1 << 2
XDP_FLAGS_HW_MODE = 1 << 3
XDP_FLAGS_REPLACE = 1 << 4
XDP_FLAGS_MODES = XDP_FLAGS_SKB_MODE | XDP_FLAGS_DRV_MODE | XDP_FLAGS_HW_MODE
XDP_FLAGS_MASK = XDP_FLAGS_UPDATE_IF_NOEXIST | XDP_FLAGS_MODES | XDP_FLAGS_REPLACE

# IFLA_XDP Attributes
IFLA_XDP_UNSPEC = 0
IFLA_XDP_FD = 1
IFLA_XDP_ATTACHED = 2
IFLA_XDP_FLAGS = 3
IFLA_XDP_PROG_ID = 4
IFLA_XDP_DRV_PROG_ID = 5
IFLA_XDP_SKB_PROG_ID = 6
IFLA_XDP_HW_PROG_ID = 7
IFLA_XDP_EXPECTED_FD = 8
IFLA_XDP_MAX = 8

# Multicast Group Index
RTNLGRP_LINK = 1

# Protocol-specific constants
SOL_NETLINK = getattr(socket, 'SOL_NETLINK', 270)  # Default to 270 for Netlink-specific socket options

# General constants
NLMSG_MIN_TYPE = 0x10

GENL_NAMSIZ = 16  # Length of family name
GENL_MIN_ID = NLMSG_MIN_TYPE
GENL_MAX_ID = 1023

GENL_ADMIN_PERM = 0x01
GENL_CMD_CAP_DO = 0x02
GENL_CMD_CAP_DUMP = 0x04
GENL_CMD_CAP_HASPOL = 0x08

# Reserved static generic netlink identifiers
GENL_ID_GENERATE = 0
GENL_ID_CTRL = NLMSG_MIN_TYPE

# Controller commands
CTRL_CMD_UNSPEC = 0x0
CTRL_CMD_NEWFAMILY = 0x1
CTRL_CMD_DELFAMILY = 0x2
CTRL_CMD_GETFAMILY = 0x3
CTRL_CMD_NEWOPS = 0x4
CTRL_CMD_DELOPS = 0x5
CTRL_CMD_GETOPS = 0x6
CTRL_CMD_NEWMCAST_GRP = 0x7
CTRL_CMD_DELMCAST_GRP = 0x8
CTRL_CMD_GETMCAST_GRP = 0x9
CTRL_CMD_GETPOLICY = 0xA

# Controller attributes
CTRL_ATTR_UNSPEC = 0x0
CTRL_ATTR_FAMILY_ID = 0x1
CTRL_ATTR_FAMILY_NAME = 0x2
CTRL_ATTR_VERSION = 0x3
CTRL_ATTR_HDRSIZE = 0x4
CTRL_ATTR_MAXATTR = 0x5
CTRL_ATTR_OPS = 0x6
CTRL_ATTR_MCAST_GROUPS = 0x7
CTRL_ATTR_POLICY = 0x8
CTRL_ATTR_OP_POLICY = 0x9
CTRL_ATTR_OP = 0xA

CTRL_ATTR_OP_UNSPEC = 0x0
CTRL_ATTR_OP_ID = 0x1
CTRL_ATTR_OP_FLAGS = 0x2

CTRL_ATTR_MCAST_GRP_UNSPEC = 0x0
CTRL_ATTR_MCAST_GRP_NAME = 0x1
CTRL_ATTR_MCAST_GRP_ID = 0x2

# Netlink attribute types
NL_ATTR_TYPE_INVALID = 0
NL_ATTR_TYPE_FLAG = 1
NL_ATTR_TYPE_U8 = 2
NL_ATTR_TYPE_U16 = 3
NL_ATTR_TYPE_U32 = 4
NL_ATTR_TYPE_U64 = 5
NL_ATTR_TYPE_S8 = 6
NL_ATTR_TYPE_S16 = 7
NL_ATTR_TYPE_S32 = 8
NL_ATTR_TYPE_S64 = 9
NL_ATTR_TYPE_BINARY = 10
NL_ATTR_TYPE_STRING = 11
NL_ATTR_TYPE_NUL_STRING = 12
NL_ATTR_TYPE_NESTED = 13
NL_ATTR_TYPE_NESTED_ARRAY = 14
NL_ATTR_TYPE_BITFIELD32 = 15

# Netlink policy attributes
NL_POLICY_TYPE_ATTR_UNSPEC = 0
NL_POLICY_TYPE_ATTR_TYPE = 1
NL_POLICY_TYPE_ATTR_MIN_VALUE_S = 2
NL_POLICY_TYPE_ATTR_MAX_VALUE_S = 3
NL_POLICY_TYPE_ATTR_MIN_VALUE_U = 4
NL_POLICY_TYPE_ATTR_MAX_VALUE_U = 5
NL_POLICY_TYPE_ATTR_MIN_LENGTH = 6
NL_POLICY_TYPE_ATTR_MAX_LENGTH = 7
NL_POLICY_TYPE_ATTR_POLICY_IDX = 8
NL_POLICY_TYPE_ATTR_POLICY_MAXTYPE = 9
NL_POLICY_TYPE_ATTR_BITFIELD32_MASK = 10
NL_POLICY_TYPE_ATTR_PAD = 11
NL_POLICY_TYPE_ATTR_MASK = 12

# Netlink families
NETLINK_ROUTE = 0
NETLINK_UNUSED = 1
NETLINK_USERSOCK = 2
NETLINK_FIREWALL = 3
NETLINK_SOCK_DIAG = 4
NETLINK_NFLOG = 5
NETLINK_XFRM = 6
NETLINK_SELINUX = 7
NETLINK_ISCSI = 8
NETLINK_AUDIT = 9
NETLINK_FIB_LOOKUP = 10
NETLINK_CONNECTOR = 11
NETLINK_NETFILTER = 12
NETLINK_IP6_FW = 13
NETLINK_DNRTMSG = 14
NETLINK_KOBJECT_UEVENT = 15
NETLINK_GENERIC = 16
NETLINK_SCSITRANSPORT = 18

# Netlink attribute flags
NLA_F_NESTED = 1 << 15
NLA_F_NET_BYTEORDER = 1 << 14

# Netlink message flags (nlmsghdr.flags)
NLM_F_REQUEST = 1
NLM_F_MULTI = 2
NLM_F_ACK = 4
NLM_F_ECHO = 8
NLM_F_DUMP_INTR = 0x10
NLM_F_DUMP_FILTERED = 0x20

# Modifiers to GET request
NLM_F_ROOT = 0x100
NLM_F_MATCH = 0x200
NLM_F_ATOMIC = 0x400
NLM_F_DUMP = NLM_F_ROOT | NLM_F_MATCH

# Modifiers to NEW request
NLM_F_REPLACE = 0x100
NLM_F_EXCL = 0x200
NLM_F_CREATE = 0x400
NLM_F_APPEND = 0x800

NLM_F_CAPPED = 0x100
NLM_F_ACK_TLVS = 0x200

# Netlink message types
NLMSG_NOOP = 0x1
NLMSG_ERROR = 0x2
NLMSG_DONE = 0x3
NLMSG_OVERRUN = 0x4
NLMSG_CONTROL = 0xE
NLMSG_TRANSPORT = 0xF
NLMSG_MIN_TYPE = 0x10
NLMSG_MAX_LEN = 0xFFFF

# Netlink header misc
NLMSG_HDR_FORMAT = "IHHII"   # length (I), type (H), flags (H), sequence (I)
NLMSG_HDR_SIZE = struct.calcsize(NLMSG_HDR_FORMAT)

# Miscellaneous
SOL_NETLINK = 270
NETLINK_ADD_MEMBERSHIP = 1
NETLINK_DROP_MEMBERSHIP = 2
NETLINK_PKTINFO = 3
NETLINK_BROADCAST_ERROR = 4
NETLINK_NO_ENOBUFS = 5
NETLINK_RX_RING = 6
NETLINK_TX_RING = 7
NETLINK_LISTEN_ALL_NSID = 8
NETLINK_EXT_ACK = 11
NETLINK_GET_STRICT_CHK = 12

#  Alignment
NLMSG_ALIGNTO = 4
def NLMSG_ALIGN(length: int) -> int:
    return (length + NLMSG_ALIGNTO - 1) & ~(NLMSG_ALIGNTO - 1)

def NLMSG_LENGTH(payload_len: int) -> int:
    return payload_len + NLMSG_ALIGN(NLMSG_HDR_SIZE)

def NLMSG_SPACE(payload_len: int) -> int:
    return NLMSG_ALIGN(NLMSG_LENGTH(payload_len))