# This file is auto-generated by tools/build_api.py
# Do not edit manually.

# Structs
from pyritex.netlink.socket import NetlinkSocket
from pyritex.netlink.message import RouteMessage
from pyritex.netlink.message import NetlinkHeader
from pyritex.netlink.message import NetlinkMessage
from pyritex.netlink.message import RtMsg

# Constants and Helpers
from pyritex.netlink.consts import AF_UNSPEC
from pyritex.netlink.consts import AF_INET
from pyritex.netlink.consts import AF_NETLINK
from pyritex.netlink.consts import AF_BRIDGE
from pyritex.netlink.consts import AF_UNIX
from pyritex.netlink.consts import AF_LOCAL
from pyritex.netlink.consts import AF_AX25
from pyritex.netlink.consts import AF_IPX
from pyritex.netlink.consts import AF_APPLETALK
from pyritex.netlink.consts import AF_NETROM
from pyritex.netlink.consts import AF_ATMPVC
from pyritex.netlink.consts import AF_X25
from pyritex.netlink.consts import AF_INET6
from pyritex.netlink.consts import AF_ROSE
from pyritex.netlink.consts import AF_DECNET
from pyritex.netlink.consts import AF_NETBEUI
from pyritex.netlink.consts import AF_SECURITY
from pyritex.netlink.consts import AF_KEY
from pyritex.netlink.consts import AF_PACKET
from pyritex.netlink.consts import AF_ASH
from pyritex.netlink.consts import AF_ECONET
from pyritex.netlink.consts import AF_ATMSVC
from pyritex.netlink.consts import AF_RDS
from pyritex.netlink.consts import AF_SNA
from pyritex.netlink.consts import AF_IRDA
from pyritex.netlink.consts import AF_PPPOX
from pyritex.netlink.consts import AF_WANPIPE
from pyritex.netlink.consts import AF_LLC
from pyritex.netlink.consts import AF_IB
from pyritex.netlink.consts import AF_MPLS
from pyritex.netlink.consts import AF_CAN
from pyritex.netlink.consts import AF_TIPC
from pyritex.netlink.consts import AF_BLUETOOTH
from pyritex.netlink.consts import AF_IUCV
from pyritex.netlink.consts import AF_RXRPC
from pyritex.netlink.consts import AF_ISDN
from pyritex.netlink.consts import AF_PHONET
from pyritex.netlink.consts import AF_IEEE802154
from pyritex.netlink.consts import AF_CAIF
from pyritex.netlink.consts import AF_ALG
from pyritex.netlink.consts import AF_NFC
from pyritex.netlink.consts import AF_VSOCK
from pyritex.netlink.consts import AF_KCM
from pyritex.netlink.consts import AF_QIPCRTR
from pyritex.netlink.consts import AF_SMC
from pyritex.netlink.consts import AF_XDP
from pyritex.netlink.consts import AF_MCTP
from pyritex.netlink.consts import AF_MAX
from pyritex.netlink.consts import PF_UNSPEC
from pyritex.netlink.consts import PF_UNIX
from pyritex.netlink.consts import PF_LOCAL
from pyritex.netlink.consts import PF_INET
from pyritex.netlink.consts import PF_AX25
from pyritex.netlink.consts import PF_IPX
from pyritex.netlink.consts import PF_APPLETALK
from pyritex.netlink.consts import PF_NETROM
from pyritex.netlink.consts import PF_BRIDGE
from pyritex.netlink.consts import PF_ATMPVC
from pyritex.netlink.consts import PF_X25
from pyritex.netlink.consts import PF_INET6
from pyritex.netlink.consts import PF_ROSE
from pyritex.netlink.consts import PF_DECNET
from pyritex.netlink.consts import PF_NETBEUI
from pyritex.netlink.consts import PF_SECURITY
from pyritex.netlink.consts import PF_KEY
from pyritex.netlink.consts import PF_NETLINK
from pyritex.netlink.consts import PF_ROUTE
from pyritex.netlink.consts import PF_PACKET
from pyritex.netlink.consts import PF_ASH
from pyritex.netlink.consts import PF_ECONET
from pyritex.netlink.consts import PF_ATMSVC
from pyritex.netlink.consts import PF_RDS
from pyritex.netlink.consts import PF_SNA
from pyritex.netlink.consts import PF_IRDA
from pyritex.netlink.consts import PF_PPPOX
from pyritex.netlink.consts import PF_WANPIPE
from pyritex.netlink.consts import PF_LLC
from pyritex.netlink.consts import PF_IB
from pyritex.netlink.consts import PF_MPLS
from pyritex.netlink.consts import PF_CAN
from pyritex.netlink.consts import PF_TIPC
from pyritex.netlink.consts import PF_BLUETOOTH
from pyritex.netlink.consts import PF_IUCV
from pyritex.netlink.consts import PF_RXRPC
from pyritex.netlink.consts import PF_ISDN
from pyritex.netlink.consts import PF_PHONET
from pyritex.netlink.consts import PF_IEEE802154
from pyritex.netlink.consts import PF_CAIF
from pyritex.netlink.consts import PF_ALG
from pyritex.netlink.consts import PF_NFC
from pyritex.netlink.consts import PF_VSOCK
from pyritex.netlink.consts import PF_KCM
from pyritex.netlink.consts import PF_QIPCRTR
from pyritex.netlink.consts import PF_SMC
from pyritex.netlink.consts import PF_XDP
from pyritex.netlink.consts import PF_MCTP
from pyritex.netlink.consts import PF_MAX
from pyritex.netlink.consts import IFF_LOWER_UP
from pyritex.netlink.consts import IFF_DORMANT
from pyritex.netlink.consts import IFLA_UNSPEC
from pyritex.netlink.consts import IFLA_ADDRESS
from pyritex.netlink.consts import IFLA_BROADCAST
from pyritex.netlink.consts import IFLA_IFNAME
from pyritex.netlink.consts import IFLA_MTU
from pyritex.netlink.consts import IFLA_LINK
from pyritex.netlink.consts import IFLA_QDISC
from pyritex.netlink.consts import IFLA_STATS
from pyritex.netlink.consts import IFLA_COST
from pyritex.netlink.consts import IFLA_PRIORITY
from pyritex.netlink.consts import IFLA_MASTER
from pyritex.netlink.consts import IFLA_WIRELESS
from pyritex.netlink.consts import IFLA_PROTINFO
from pyritex.netlink.consts import IFLA_TXQLEN
from pyritex.netlink.consts import IFLA_MAP
from pyritex.netlink.consts import IFLA_WEIGHT
from pyritex.netlink.consts import IFLA_OPERSTATE
from pyritex.netlink.consts import IFLA_LINKMODE
from pyritex.netlink.consts import IFLA_LINKINFO
from pyritex.netlink.consts import IFLA_NET_NS_PID
from pyritex.netlink.consts import IFLA_IFALIAS
from pyritex.netlink.consts import IFLA_NUM_VF
from pyritex.netlink.consts import IFLA_VFINFO_LIST
from pyritex.netlink.consts import IFLA_STATS64
from pyritex.netlink.consts import IFLA_VF_PORTS
from pyritex.netlink.consts import IFLA_PORT_SELF
from pyritex.netlink.consts import IFLA_AF_SPEC
from pyritex.netlink.consts import IFLA_GROUP
from pyritex.netlink.consts import IFLA_NET_NS_FD
from pyritex.netlink.consts import IFLA_EXT_MASK
from pyritex.netlink.consts import IFLA_PROMISCUITY
from pyritex.netlink.consts import IFLA_NUM_TX_QUEUES
from pyritex.netlink.consts import IFLA_NUM_RX_QUEUES
from pyritex.netlink.consts import IFLA_CARRIER
from pyritex.netlink.consts import IFLA_PHYS_PORT_ID
from pyritex.netlink.consts import IFLA_CARRIER_CHANGES
from pyritex.netlink.consts import IFLA_PHYS_SWITCH_ID
from pyritex.netlink.consts import IFLA_LINK_NETNSID
from pyritex.netlink.consts import IFLA_PHYS_PORT_NAME
from pyritex.netlink.consts import IFLA_PROTO_DOWN
from pyritex.netlink.consts import IFLA_GSO_MAX_SEGS
from pyritex.netlink.consts import IFLA_GSO_MAX_SIZE
from pyritex.netlink.consts import IFLA_PAD
from pyritex.netlink.consts import IFLA_XDP
from pyritex.netlink.consts import IFLA_EVENT
from pyritex.netlink.consts import IFLA_NEW_NETNSID
from pyritex.netlink.consts import IFLA_IF_NETNSID
from pyritex.netlink.consts import IFLA_CARRIER_UP_COUNT
from pyritex.netlink.consts import IFLA_CARRIER_DOWN_COUNT
from pyritex.netlink.consts import IFLA_NEW_IFINDEX
from pyritex.netlink.consts import IFLA_MIN_MTU
from pyritex.netlink.consts import IFLA_MAX_MTU
from pyritex.netlink.consts import IFLA_PROP_LIST
from pyritex.netlink.consts import IFLA_ALT_IFNAME
from pyritex.netlink.consts import IFLA_PERM_ADDRESS
from pyritex.netlink.consts import IFLA_PROTO_DOWN_REASON
from pyritex.netlink.consts import IFLA_MAX
from pyritex.netlink.consts import IF_OPER_UNKNOWN
from pyritex.netlink.consts import IF_OPER_NOTPRESENT
from pyritex.netlink.consts import IF_OPER_DOWN
from pyritex.netlink.consts import IF_OPER_LOWERLAYERDOWN
from pyritex.netlink.consts import IF_OPER_TESTING
from pyritex.netlink.consts import IF_OPER_DORMANT
from pyritex.netlink.consts import IF_OPER_UP
from pyritex.netlink.consts import LINK_XSTATS_TYPE_UNSPEC
from pyritex.netlink.consts import LINK_XSTATS_TYPE_BRIDGE
from pyritex.netlink.consts import LINK_XSTATS_TYPE_BOND
from pyritex.netlink.consts import LINK_XSTATS_TYPE_MAX
from pyritex.netlink.consts import XDP_ATTACHED_NONE
from pyritex.netlink.consts import XDP_ATTACHED_DRV
from pyritex.netlink.consts import XDP_ATTACHED_SKB
from pyritex.netlink.consts import XDP_ATTACHED_HW
from pyritex.netlink.consts import XDP_ATTACHED_MULTI
from pyritex.netlink.consts import XDP_FLAGS_UPDATE_IF_NOEXIST
from pyritex.netlink.consts import XDP_FLAGS_SKB_MODE
from pyritex.netlink.consts import XDP_FLAGS_DRV_MODE
from pyritex.netlink.consts import XDP_FLAGS_HW_MODE
from pyritex.netlink.consts import XDP_FLAGS_REPLACE
from pyritex.netlink.consts import XDP_FLAGS_MODES
from pyritex.netlink.consts import XDP_FLAGS_MASK
from pyritex.netlink.consts import IFLA_XDP_UNSPEC
from pyritex.netlink.consts import IFLA_XDP_FD
from pyritex.netlink.consts import IFLA_XDP_ATTACHED
from pyritex.netlink.consts import IFLA_XDP_FLAGS
from pyritex.netlink.consts import IFLA_XDP_PROG_ID
from pyritex.netlink.consts import IFLA_XDP_DRV_PROG_ID
from pyritex.netlink.consts import IFLA_XDP_SKB_PROG_ID
from pyritex.netlink.consts import IFLA_XDP_HW_PROG_ID
from pyritex.netlink.consts import IFLA_XDP_EXPECTED_FD
from pyritex.netlink.consts import IFLA_XDP_MAX
from pyritex.netlink.consts import RTNLGRP_LINK
from pyritex.netlink.consts import SOL_NETLINK
from pyritex.netlink.consts import NLMSG_MIN_TYPE
from pyritex.netlink.consts import GENL_NAMSIZ
from pyritex.netlink.consts import GENL_MIN_ID
from pyritex.netlink.consts import GENL_MAX_ID
from pyritex.netlink.consts import GENL_ADMIN_PERM
from pyritex.netlink.consts import GENL_CMD_CAP_DO
from pyritex.netlink.consts import GENL_CMD_CAP_DUMP
from pyritex.netlink.consts import GENL_CMD_CAP_HASPOL
from pyritex.netlink.consts import GENL_ID_GENERATE
from pyritex.netlink.consts import GENL_ID_CTRL
from pyritex.netlink.consts import CTRL_CMD_UNSPEC
from pyritex.netlink.consts import CTRL_CMD_NEWFAMILY
from pyritex.netlink.consts import CTRL_CMD_DELFAMILY
from pyritex.netlink.consts import CTRL_CMD_GETFAMILY
from pyritex.netlink.consts import CTRL_CMD_NEWOPS
from pyritex.netlink.consts import CTRL_CMD_DELOPS
from pyritex.netlink.consts import CTRL_CMD_GETOPS
from pyritex.netlink.consts import CTRL_CMD_NEWMCAST_GRP
from pyritex.netlink.consts import CTRL_CMD_DELMCAST_GRP
from pyritex.netlink.consts import CTRL_CMD_GETMCAST_GRP
from pyritex.netlink.consts import CTRL_CMD_GETPOLICY
from pyritex.netlink.consts import CTRL_ATTR_UNSPEC
from pyritex.netlink.consts import CTRL_ATTR_FAMILY_ID
from pyritex.netlink.consts import CTRL_ATTR_FAMILY_NAME
from pyritex.netlink.consts import CTRL_ATTR_VERSION
from pyritex.netlink.consts import CTRL_ATTR_HDRSIZE
from pyritex.netlink.consts import CTRL_ATTR_MAXATTR
from pyritex.netlink.consts import CTRL_ATTR_OPS
from pyritex.netlink.consts import CTRL_ATTR_MCAST_GROUPS
from pyritex.netlink.consts import CTRL_ATTR_POLICY
from pyritex.netlink.consts import CTRL_ATTR_OP_POLICY
from pyritex.netlink.consts import CTRL_ATTR_OP
from pyritex.netlink.consts import CTRL_ATTR_OP_UNSPEC
from pyritex.netlink.consts import CTRL_ATTR_OP_ID
from pyritex.netlink.consts import CTRL_ATTR_OP_FLAGS
from pyritex.netlink.consts import CTRL_ATTR_MCAST_GRP_UNSPEC
from pyritex.netlink.consts import CTRL_ATTR_MCAST_GRP_NAME
from pyritex.netlink.consts import CTRL_ATTR_MCAST_GRP_ID
from pyritex.netlink.consts import NL_ATTR_TYPE_INVALID
from pyritex.netlink.consts import NL_ATTR_TYPE_FLAG
from pyritex.netlink.consts import NL_ATTR_TYPE_U8
from pyritex.netlink.consts import NL_ATTR_TYPE_U16
from pyritex.netlink.consts import NL_ATTR_TYPE_U32
from pyritex.netlink.consts import NL_ATTR_TYPE_U64
from pyritex.netlink.consts import NL_ATTR_TYPE_S8
from pyritex.netlink.consts import NL_ATTR_TYPE_S16
from pyritex.netlink.consts import NL_ATTR_TYPE_S32
from pyritex.netlink.consts import NL_ATTR_TYPE_S64
from pyritex.netlink.consts import NL_ATTR_TYPE_BINARY
from pyritex.netlink.consts import NL_ATTR_TYPE_STRING
from pyritex.netlink.consts import NL_ATTR_TYPE_NUL_STRING
from pyritex.netlink.consts import NL_ATTR_TYPE_NESTED
from pyritex.netlink.consts import NL_ATTR_TYPE_NESTED_ARRAY
from pyritex.netlink.consts import NL_ATTR_TYPE_BITFIELD32
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_UNSPEC
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_TYPE
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_MIN_VALUE_S
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_MAX_VALUE_S
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_MIN_VALUE_U
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_MAX_VALUE_U
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_MIN_LENGTH
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_MAX_LENGTH
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_POLICY_IDX
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_POLICY_MAXTYPE
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_BITFIELD32_MASK
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_PAD
from pyritex.netlink.consts import NL_POLICY_TYPE_ATTR_MASK
from pyritex.netlink.consts import NETLINK_ROUTE
from pyritex.netlink.consts import NETLINK_UNUSED
from pyritex.netlink.consts import NETLINK_USERSOCK
from pyritex.netlink.consts import NETLINK_FIREWALL
from pyritex.netlink.consts import NETLINK_SOCK_DIAG
from pyritex.netlink.consts import NETLINK_NFLOG
from pyritex.netlink.consts import NETLINK_XFRM
from pyritex.netlink.consts import NETLINK_SELINUX
from pyritex.netlink.consts import NETLINK_ISCSI
from pyritex.netlink.consts import NETLINK_AUDIT
from pyritex.netlink.consts import NETLINK_FIB_LOOKUP
from pyritex.netlink.consts import NETLINK_CONNECTOR
from pyritex.netlink.consts import NETLINK_NETFILTER
from pyritex.netlink.consts import NETLINK_IP6_FW
from pyritex.netlink.consts import NETLINK_DNRTMSG
from pyritex.netlink.consts import NETLINK_KOBJECT_UEVENT
from pyritex.netlink.consts import NETLINK_GENERIC
from pyritex.netlink.consts import NETLINK_SCSITRANSPORT
from pyritex.netlink.consts import NLA_F_NESTED
from pyritex.netlink.consts import NLA_F_NET_BYTEORDER
from pyritex.netlink.consts import NLM_F_REQUEST
from pyritex.netlink.consts import NLM_F_MULTI
from pyritex.netlink.consts import NLM_F_ACK
from pyritex.netlink.consts import NLM_F_ECHO
from pyritex.netlink.consts import NLM_F_DUMP_INTR
from pyritex.netlink.consts import NLM_F_DUMP_FILTERED
from pyritex.netlink.consts import NLM_F_ROOT
from pyritex.netlink.consts import NLM_F_MATCH
from pyritex.netlink.consts import NLM_F_ATOMIC
from pyritex.netlink.consts import NLM_F_DUMP
from pyritex.netlink.consts import NLM_F_REPLACE
from pyritex.netlink.consts import NLM_F_EXCL
from pyritex.netlink.consts import NLM_F_CREATE
from pyritex.netlink.consts import NLM_F_APPEND
from pyritex.netlink.consts import NLM_F_CAPPED
from pyritex.netlink.consts import NLM_F_ACK_TLVS
from pyritex.netlink.consts import NLMSG_NOOP
from pyritex.netlink.consts import NLMSG_ERROR
from pyritex.netlink.consts import NLMSG_DONE
from pyritex.netlink.consts import NLMSG_OVERRUN
from pyritex.netlink.consts import NLMSG_CONTROL
from pyritex.netlink.consts import NLMSG_TRANSPORT
from pyritex.netlink.consts import NLMSG_MIN_TYPE
from pyritex.netlink.consts import NLMSG_MAX_LEN
from pyritex.netlink.consts import NLMSG_HDR_FORMAT
from pyritex.netlink.consts import NLMSG_HDR_SIZE
from pyritex.netlink.consts import SOL_NETLINK
from pyritex.netlink.consts import NETLINK_ADD_MEMBERSHIP
from pyritex.netlink.consts import NETLINK_DROP_MEMBERSHIP
from pyritex.netlink.consts import NETLINK_PKTINFO
from pyritex.netlink.consts import NETLINK_BROADCAST_ERROR
from pyritex.netlink.consts import NETLINK_NO_ENOBUFS
from pyritex.netlink.consts import NETLINK_RX_RING
from pyritex.netlink.consts import NETLINK_TX_RING
from pyritex.netlink.consts import NETLINK_LISTEN_ALL_NSID
from pyritex.netlink.consts import NETLINK_EXT_ACK
from pyritex.netlink.consts import NETLINK_GET_STRICT_CHK
from pyritex.netlink.consts import NLMSG_ALIGNTO
from pyritex.netlink.rtnl.consts import RTM_BASE
from pyritex.netlink.rtnl.consts import RTM_NEWLINK
from pyritex.netlink.rtnl.consts import RTM_DELLINK
from pyritex.netlink.rtnl.consts import RTM_GETLINK
from pyritex.netlink.rtnl.consts import RTM_SETLINK
from pyritex.netlink.rtnl.consts import RTM_NEWADDR
from pyritex.netlink.rtnl.consts import RTM_DELADDR
from pyritex.netlink.rtnl.consts import RTM_GETADDR
from pyritex.netlink.rtnl.consts import RTM_NEWROUTE
from pyritex.netlink.rtnl.consts import RTM_DELROUTE
from pyritex.netlink.rtnl.consts import RTM_GETROUTE
from pyritex.netlink.rtnl.consts import RTM_NEWNEIGH
from pyritex.netlink.rtnl.consts import RTM_DELNEIGH
from pyritex.netlink.rtnl.consts import RTM_GETNEIGH
from pyritex.netlink.rtnl.consts import RTM_NEWRULE
from pyritex.netlink.rtnl.consts import RTM_DELRULE
from pyritex.netlink.rtnl.consts import RTM_GETRULE
from pyritex.netlink.rtnl.consts import RTM_NEWQDISC
from pyritex.netlink.rtnl.consts import RTM_DELQDISC
from pyritex.netlink.rtnl.consts import RTM_GETQDISC
from pyritex.netlink.rtnl.consts import RTM_NEWTCLASS
from pyritex.netlink.rtnl.consts import RTM_DELTCLASS
from pyritex.netlink.rtnl.consts import RTM_GETTCLASS
from pyritex.netlink.rtnl.consts import RTM_NEWTFILTER
from pyritex.netlink.rtnl.consts import RTM_DELTFILTER
from pyritex.netlink.rtnl.consts import RTM_GETTFILTER
from pyritex.netlink.rtnl.consts import RTM_NEWACTION
from pyritex.netlink.rtnl.consts import RTM_DELACTION
from pyritex.netlink.rtnl.consts import RTM_GETACTION
from pyritex.netlink.rtnl.consts import RTM_NEWPREFIX
from pyritex.netlink.rtnl.consts import RTM_GETMULTICAST
from pyritex.netlink.rtnl.consts import RTM_GETANYCAST
from pyritex.netlink.rtnl.consts import RTM_NEWNEIGHTBL
from pyritex.netlink.rtnl.consts import RTM_GETNEIGHTBL
from pyritex.netlink.rtnl.consts import RTM_SETNEIGHTBL
from pyritex.netlink.rtnl.consts import RTM_NEWNDUSEROPT
from pyritex.netlink.rtnl.consts import RTM_NEWADDRLABEL
from pyritex.netlink.rtnl.consts import RTM_DELADDRLABEL
from pyritex.netlink.rtnl.consts import RTM_GETADDRLABEL
from pyritex.netlink.rtnl.consts import RTM_GETDCB
from pyritex.netlink.rtnl.consts import RTM_SETDCB
from pyritex.netlink.rtnl.consts import __RTM_MAX
from pyritex.netlink.rtnl.consts import RTM_MAX
from pyritex.netlink.rtnl.consts import RTM_NR_MSGTYPES
from pyritex.netlink.rtnl.consts import RTM_NR_FAMILIES
from pyritex.netlink.rtnl.consts import RTA_ALIGNTO
from pyritex.netlink.rtnl.consts import RTN_UNSPEC
from pyritex.netlink.rtnl.consts import RTN_UNICAST
from pyritex.netlink.rtnl.consts import RTN_LOCAL
from pyritex.netlink.rtnl.consts import RTN_BROADCAST
from pyritex.netlink.rtnl.consts import RTN_ANYCAST
from pyritex.netlink.rtnl.consts import RTN_MULTICAST
from pyritex.netlink.rtnl.consts import RTN_BLACKHOLE
from pyritex.netlink.rtnl.consts import RTN_UNREACHABLE
from pyritex.netlink.rtnl.consts import RTN_PROHIBIT
from pyritex.netlink.rtnl.consts import RTN_THROW
from pyritex.netlink.rtnl.consts import RTN_NAT
from pyritex.netlink.rtnl.consts import RTN_XRESOLVE
from pyritex.netlink.rtnl.consts import __RTN_MAX
from pyritex.netlink.rtnl.consts import RTN_MAX
from pyritex.netlink.rtnl.consts import RTPROT_UNSPEC
from pyritex.netlink.rtnl.consts import RTPROT_REDIRECT
from pyritex.netlink.rtnl.consts import RTPROT_KERNEL
from pyritex.netlink.rtnl.consts import RTPROT_BOOT
from pyritex.netlink.rtnl.consts import RTPROT_STATIC
from pyritex.netlink.rtnl.consts import RTPROT_GATED
from pyritex.netlink.rtnl.consts import RTPROT_RA
from pyritex.netlink.rtnl.consts import RTPROT_MRT
from pyritex.netlink.rtnl.consts import RTPROT_ZEBRA
from pyritex.netlink.rtnl.consts import RTPROT_BIRD
from pyritex.netlink.rtnl.consts import RTPROT_DNROUTED
from pyritex.netlink.rtnl.consts import RTPROT_XORP
from pyritex.netlink.rtnl.consts import RTPROT_NTK
from pyritex.netlink.rtnl.consts import RTPROT_DHCP
from pyritex.netlink.rtnl.consts import RT_SCOPE_UNIVERSE
from pyritex.netlink.rtnl.consts import RT_SCOPE_SITE
from pyritex.netlink.rtnl.consts import RT_SCOPE_LINK
from pyritex.netlink.rtnl.consts import RT_SCOPE_HOST
from pyritex.netlink.rtnl.consts import RT_SCOPE_NOWHERE
from pyritex.netlink.rtnl.consts import RTM_F_NOTIFY
from pyritex.netlink.rtnl.consts import RTM_F_CLONED
from pyritex.netlink.rtnl.consts import RTM_F_EQUALIZE
from pyritex.netlink.rtnl.consts import RTM_F_PREFIX
from pyritex.netlink.rtnl.consts import RT_TABLE_UNSPEC
from pyritex.netlink.rtnl.consts import RT_TABLE_COMPAT
from pyritex.netlink.rtnl.consts import RT_TABLE_DEFAULT
from pyritex.netlink.rtnl.consts import RT_TABLE_MAIN
from pyritex.netlink.rtnl.consts import RT_TABLE_LOCAL
from pyritex.netlink.rtnl.consts import RT_TABLE_MAX
from pyritex.netlink.rtnl.consts import RTA_UNSPEC
from pyritex.netlink.rtnl.consts import RTA_DST
from pyritex.netlink.rtnl.consts import RTA_SRC
from pyritex.netlink.rtnl.consts import RTA_IIF
from pyritex.netlink.rtnl.consts import RTA_OIF
from pyritex.netlink.rtnl.consts import RTA_GATEWAY
from pyritex.netlink.rtnl.consts import RTA_PRIORITY
from pyritex.netlink.rtnl.consts import RTA_PREFSRC
from pyritex.netlink.rtnl.consts import RTA_METRICS
from pyritex.netlink.rtnl.consts import RTA_MULTIPATH
from pyritex.netlink.rtnl.consts import RTA_PROTOINFO
from pyritex.netlink.rtnl.consts import RTA_FLOW
from pyritex.netlink.rtnl.consts import RTA_CACHEINFO
from pyritex.netlink.rtnl.consts import RTA_SESSION
from pyritex.netlink.rtnl.consts import RTA_MP_ALGO
from pyritex.netlink.rtnl.consts import RTA_TABLE
from pyritex.netlink.rtnl.consts import __RTA_MAX
from pyritex.netlink.rtnl.consts import RTA_MAX
from pyritex.netlink.rtnl.consts import RTNH_F_DEAD
from pyritex.netlink.rtnl.consts import RTNH_F_PERVASIVE
from pyritex.netlink.rtnl.consts import RTNH_F_ONLINK
from pyritex.netlink.rtnl.consts import RTNH_ALIGNTO
from pyritex.netlink.rtnl.consts import RTAX_UNSPEC
from pyritex.netlink.rtnl.consts import RTAX_LOCK
from pyritex.netlink.rtnl.consts import RTAX_MTU
from pyritex.netlink.rtnl.consts import RTAX_WINDOW
from pyritex.netlink.rtnl.consts import RTAX_RTT
from pyritex.netlink.rtnl.consts import RTAX_RTTVAR
from pyritex.netlink.rtnl.consts import RTAX_SSTHRESH
from pyritex.netlink.rtnl.consts import RTAX_CWND
from pyritex.netlink.rtnl.consts import RTAX_ADVMSS
from pyritex.netlink.rtnl.consts import RTAX_REORDERING
from pyritex.netlink.rtnl.consts import RTAX_HOPLIMIT
from pyritex.netlink.rtnl.consts import RTAX_INITCWND
from pyritex.netlink.rtnl.consts import RTAX_FEATURES
from pyritex.netlink.rtnl.consts import RTAX_RTO_MIN
from pyritex.netlink.rtnl.consts import __RTAX_MAX
from pyritex.netlink.rtnl.consts import RTAX_MAX
from pyritex.netlink.rtnl.consts import RTAX_FEATURE_ECN
from pyritex.netlink.rtnl.consts import RTAX_FEATURE_SACK
from pyritex.netlink.rtnl.consts import RTAX_FEATURE_TIMESTAMP
from pyritex.netlink.rtnl.consts import RTAX_FEATURE_ALLFRAG
from pyritex.netlink.rtnl.consts import PREFIX_UNSPEC
from pyritex.netlink.rtnl.consts import PREFIX_ADDRESS
from pyritex.netlink.rtnl.consts import PREFIX_CACHEINFO
from pyritex.netlink.rtnl.consts import __PREFIX_MAX
from pyritex.netlink.rtnl.consts import PREFIX_MAX
from pyritex.netlink.rtnl.consts import TCA_UNSPEC
from pyritex.netlink.rtnl.consts import TCA_KIND
from pyritex.netlink.rtnl.consts import TCA_OPTIONS
from pyritex.netlink.rtnl.consts import TCA_STATS
from pyritex.netlink.rtnl.consts import TCA_XSTATS
from pyritex.netlink.rtnl.consts import TCA_RATE
from pyritex.netlink.rtnl.consts import TCA_FCNT
from pyritex.netlink.rtnl.consts import TCA_STATS2
from pyritex.netlink.rtnl.consts import TCA_STAB
from pyritex.netlink.rtnl.consts import __TCA_MAX
from pyritex.netlink.rtnl.consts import TCA_MAX
from pyritex.netlink.rtnl.consts import NDUSEROPT_UNSPEC
from pyritex.netlink.rtnl.consts import NDUSEROPT_SRCADDR
from pyritex.netlink.rtnl.consts import __NDUSEROPT_MAX
from pyritex.netlink.rtnl.consts import NDUSEROPT_MAX
from pyritex.netlink.rtnl.consts import RTMGRP_LINK
from pyritex.netlink.rtnl.consts import RTMGRP_NOTIFY
from pyritex.netlink.rtnl.consts import RTMGRP_NEIGH
from pyritex.netlink.rtnl.consts import RTMGRP_TC
from pyritex.netlink.rtnl.consts import RTMGRP_IPV4_IFADDR
from pyritex.netlink.rtnl.consts import RTMGRP_IPV4_MROUTE
from pyritex.netlink.rtnl.consts import RTMGRP_IPV4_ROUTE
from pyritex.netlink.rtnl.consts import RTMGRP_IPV4_RULE
from pyritex.netlink.rtnl.consts import RTMGRP_IPV6_IFADDR
from pyritex.netlink.rtnl.consts import RTMGRP_IPV6_MROUTE
from pyritex.netlink.rtnl.consts import RTMGRP_IPV6_ROUTE
from pyritex.netlink.rtnl.consts import RTMGRP_IPV6_IFINFO
from pyritex.netlink.rtnl.consts import RTMGRP_IPV6_PREFIX
from pyritex.netlink.rtnl.consts import RTNLGRP_NONE
from pyritex.netlink.rtnl.consts import RTNLGRP_LINK
from pyritex.netlink.rtnl.consts import RTNLGRP_NOTIFY
from pyritex.netlink.rtnl.consts import RTNLGRP_NEIGH
from pyritex.netlink.rtnl.consts import RTNLGRP_TC
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV4_IFADDR
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV4_MROUTE
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV4_ROUTE
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV4_RULE
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV6_IFADDR
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV6_MROUTE
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV6_ROUTE
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV6_IFINFO
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV6_PREFIX
from pyritex.netlink.rtnl.consts import RTNLGRP_IPV6_RULE
from pyritex.netlink.rtnl.consts import RTNLGRP_ND_USEROPT
from pyritex.netlink.rtnl.consts import RTNLGRP_PHONET_IFADDR
from pyritex.netlink.rtnl.consts import RTNLGRP_PHONET_ROUTE
from pyritex.netlink.rtnl.consts import __RTNLGRP_MAX
from pyritex.netlink.rtnl.consts import RTNLGRP_MAX
from pyritex.netlink.consts import NLMSG_ALIGN
from pyritex.netlink.consts import NLMSG_LENGTH
from pyritex.netlink.consts import NLMSG_SPACE
from pyritex.log import set_pyritex_log_level

__all__ = [
    "NetlinkSocket",
    "RouteMessage",
    "NetlinkHeader",
    "RtMsg",
    "AF_UNSPEC",
    "AF_INET",
    "AF_NETLINK",
    "AF_BRIDGE",
    "AF_UNIX",
    "AF_LOCAL",
    "AF_AX25",
    "AF_IPX",
    "AF_APPLETALK",
    "AF_NETROM",
    "AF_ATMPVC",
    "AF_X25",
    "AF_INET6",
    "AF_ROSE",
    "AF_DECNET",
    "AF_NETBEUI",
    "AF_SECURITY",
    "AF_KEY",
    "AF_PACKET",
    "AF_ASH",
    "AF_ECONET",
    "AF_ATMSVC",
    "AF_RDS",
    "AF_SNA",
    "AF_IRDA",
    "AF_PPPOX",
    "AF_WANPIPE",
    "AF_LLC",
    "AF_IB",
    "AF_MPLS",
    "AF_CAN",
    "AF_TIPC",
    "AF_BLUETOOTH",
    "AF_IUCV",
    "AF_RXRPC",
    "AF_ISDN",
    "AF_PHONET",
    "AF_IEEE802154",
    "AF_CAIF",
    "AF_ALG",
    "AF_NFC",
    "AF_VSOCK",
    "AF_KCM",
    "AF_QIPCRTR",
    "AF_SMC",
    "AF_XDP",
    "AF_MCTP",
    "AF_MAX",
    "PF_UNSPEC",
    "PF_UNIX",
    "PF_LOCAL",
    "PF_INET",
    "PF_AX25",
    "PF_IPX",
    "PF_APPLETALK",
    "PF_NETROM",
    "PF_BRIDGE",
    "PF_ATMPVC",
    "PF_X25",
    "PF_INET6",
    "PF_ROSE",
    "PF_DECNET",
    "PF_NETBEUI",
    "PF_SECURITY",
    "PF_KEY",
    "PF_NETLINK",
    "PF_ROUTE",
    "PF_PACKET",
    "PF_ASH",
    "PF_ECONET",
    "PF_ATMSVC",
    "PF_RDS",
    "PF_SNA",
    "PF_IRDA",
    "PF_PPPOX",
    "PF_WANPIPE",
    "PF_LLC",
    "PF_IB",
    "PF_MPLS",
    "PF_CAN",
    "PF_TIPC",
    "PF_BLUETOOTH",
    "PF_IUCV",
    "PF_RXRPC",
    "PF_ISDN",
    "PF_PHONET",
    "PF_IEEE802154",
    "PF_CAIF",
    "PF_ALG",
    "PF_NFC",
    "PF_VSOCK",
    "PF_KCM",
    "PF_QIPCRTR",
    "PF_SMC",
    "PF_XDP",
    "PF_MCTP",
    "PF_MAX",
    "IFF_LOWER_UP",
    "IFF_DORMANT",
    "IFLA_UNSPEC",
    "IFLA_ADDRESS",
    "IFLA_BROADCAST",
    "IFLA_IFNAME",
    "IFLA_MTU",
    "IFLA_LINK",
    "IFLA_QDISC",
    "IFLA_STATS",
    "IFLA_COST",
    "IFLA_PRIORITY",
    "IFLA_MASTER",
    "IFLA_WIRELESS",
    "IFLA_PROTINFO",
    "IFLA_TXQLEN",
    "IFLA_MAP",
    "IFLA_WEIGHT",
    "IFLA_OPERSTATE",
    "IFLA_LINKMODE",
    "IFLA_LINKINFO",
    "IFLA_NET_NS_PID",
    "IFLA_IFALIAS",
    "IFLA_NUM_VF",
    "IFLA_VFINFO_LIST",
    "IFLA_STATS64",
    "IFLA_VF_PORTS",
    "IFLA_PORT_SELF",
    "IFLA_AF_SPEC",
    "IFLA_GROUP",
    "IFLA_NET_NS_FD",
    "IFLA_EXT_MASK",
    "IFLA_PROMISCUITY",
    "IFLA_NUM_TX_QUEUES",
    "IFLA_NUM_RX_QUEUES",
    "IFLA_CARRIER",
    "IFLA_PHYS_PORT_ID",
    "IFLA_CARRIER_CHANGES",
    "IFLA_PHYS_SWITCH_ID",
    "IFLA_LINK_NETNSID",
    "IFLA_PHYS_PORT_NAME",
    "IFLA_PROTO_DOWN",
    "IFLA_GSO_MAX_SEGS",
    "IFLA_GSO_MAX_SIZE",
    "IFLA_PAD",
    "IFLA_XDP",
    "IFLA_EVENT",
    "IFLA_NEW_NETNSID",
    "IFLA_IF_NETNSID",
    "IFLA_CARRIER_UP_COUNT",
    "IFLA_CARRIER_DOWN_COUNT",
    "IFLA_NEW_IFINDEX",
    "IFLA_MIN_MTU",
    "IFLA_MAX_MTU",
    "IFLA_PROP_LIST",
    "IFLA_ALT_IFNAME",
    "IFLA_PERM_ADDRESS",
    "IFLA_PROTO_DOWN_REASON",
    "IFLA_MAX",
    "IF_OPER_UNKNOWN",
    "IF_OPER_NOTPRESENT",
    "IF_OPER_DOWN",
    "IF_OPER_LOWERLAYERDOWN",
    "IF_OPER_TESTING",
    "IF_OPER_DORMANT",
    "IF_OPER_UP",
    "LINK_XSTATS_TYPE_UNSPEC",
    "LINK_XSTATS_TYPE_BRIDGE",
    "LINK_XSTATS_TYPE_BOND",
    "LINK_XSTATS_TYPE_MAX",
    "XDP_ATTACHED_NONE",
    "XDP_ATTACHED_DRV",
    "XDP_ATTACHED_SKB",
    "XDP_ATTACHED_HW",
    "XDP_ATTACHED_MULTI",
    "XDP_FLAGS_UPDATE_IF_NOEXIST",
    "XDP_FLAGS_SKB_MODE",
    "XDP_FLAGS_DRV_MODE",
    "XDP_FLAGS_HW_MODE",
    "XDP_FLAGS_REPLACE",
    "XDP_FLAGS_MODES",
    "XDP_FLAGS_MASK",
    "IFLA_XDP_UNSPEC",
    "IFLA_XDP_FD",
    "IFLA_XDP_ATTACHED",
    "IFLA_XDP_FLAGS",
    "IFLA_XDP_PROG_ID",
    "IFLA_XDP_DRV_PROG_ID",
    "IFLA_XDP_SKB_PROG_ID",
    "IFLA_XDP_HW_PROG_ID",
    "IFLA_XDP_EXPECTED_FD",
    "IFLA_XDP_MAX",
    "RTNLGRP_LINK",
    "SOL_NETLINK",
    "NLMSG_MIN_TYPE",
    "GENL_NAMSIZ",
    "GENL_MIN_ID",
    "GENL_MAX_ID",
    "GENL_ADMIN_PERM",
    "GENL_CMD_CAP_DO",
    "GENL_CMD_CAP_DUMP",
    "GENL_CMD_CAP_HASPOL",
    "GENL_ID_GENERATE",
    "GENL_ID_CTRL",
    "CTRL_CMD_UNSPEC",
    "CTRL_CMD_NEWFAMILY",
    "CTRL_CMD_DELFAMILY",
    "CTRL_CMD_GETFAMILY",
    "CTRL_CMD_NEWOPS",
    "CTRL_CMD_DELOPS",
    "CTRL_CMD_GETOPS",
    "CTRL_CMD_NEWMCAST_GRP",
    "CTRL_CMD_DELMCAST_GRP",
    "CTRL_CMD_GETMCAST_GRP",
    "CTRL_CMD_GETPOLICY",
    "CTRL_ATTR_UNSPEC",
    "CTRL_ATTR_FAMILY_ID",
    "CTRL_ATTR_FAMILY_NAME",
    "CTRL_ATTR_VERSION",
    "CTRL_ATTR_HDRSIZE",
    "CTRL_ATTR_MAXATTR",
    "CTRL_ATTR_OPS",
    "CTRL_ATTR_MCAST_GROUPS",
    "CTRL_ATTR_POLICY",
    "CTRL_ATTR_OP_POLICY",
    "CTRL_ATTR_OP",
    "CTRL_ATTR_OP_UNSPEC",
    "CTRL_ATTR_OP_ID",
    "CTRL_ATTR_OP_FLAGS",
    "CTRL_ATTR_MCAST_GRP_UNSPEC",
    "CTRL_ATTR_MCAST_GRP_NAME",
    "CTRL_ATTR_MCAST_GRP_ID",
    "NL_ATTR_TYPE_INVALID",
    "NL_ATTR_TYPE_FLAG",
    "NL_ATTR_TYPE_U8",
    "NL_ATTR_TYPE_U16",
    "NL_ATTR_TYPE_U32",
    "NL_ATTR_TYPE_U64",
    "NL_ATTR_TYPE_S8",
    "NL_ATTR_TYPE_S16",
    "NL_ATTR_TYPE_S32",
    "NL_ATTR_TYPE_S64",
    "NL_ATTR_TYPE_BINARY",
    "NL_ATTR_TYPE_STRING",
    "NL_ATTR_TYPE_NUL_STRING",
    "NL_ATTR_TYPE_NESTED",
    "NL_ATTR_TYPE_NESTED_ARRAY",
    "NL_ATTR_TYPE_BITFIELD32",
    "NL_POLICY_TYPE_ATTR_UNSPEC",
    "NL_POLICY_TYPE_ATTR_TYPE",
    "NL_POLICY_TYPE_ATTR_MIN_VALUE_S",
    "NL_POLICY_TYPE_ATTR_MAX_VALUE_S",
    "NL_POLICY_TYPE_ATTR_MIN_VALUE_U",
    "NL_POLICY_TYPE_ATTR_MAX_VALUE_U",
    "NL_POLICY_TYPE_ATTR_MIN_LENGTH",
    "NL_POLICY_TYPE_ATTR_MAX_LENGTH",
    "NL_POLICY_TYPE_ATTR_POLICY_IDX",
    "NL_POLICY_TYPE_ATTR_POLICY_MAXTYPE",
    "NL_POLICY_TYPE_ATTR_BITFIELD32_MASK",
    "NL_POLICY_TYPE_ATTR_PAD",
    "NL_POLICY_TYPE_ATTR_MASK",
    "NETLINK_ROUTE",
    "NETLINK_UNUSED",
    "NETLINK_USERSOCK",
    "NETLINK_FIREWALL",
    "NETLINK_SOCK_DIAG",
    "NETLINK_NFLOG",
    "NETLINK_XFRM",
    "NETLINK_SELINUX",
    "NETLINK_ISCSI",
    "NETLINK_AUDIT",
    "NETLINK_FIB_LOOKUP",
    "NETLINK_CONNECTOR",
    "NETLINK_NETFILTER",
    "NETLINK_IP6_FW",
    "NETLINK_DNRTMSG",
    "NETLINK_KOBJECT_UEVENT",
    "NETLINK_GENERIC",
    "NETLINK_SCSITRANSPORT",
    "NLA_F_NESTED",
    "NLA_F_NET_BYTEORDER",
    "NLM_F_REQUEST",
    "NLM_F_MULTI",
    "NLM_F_ACK",
    "NLM_F_ECHO",
    "NLM_F_DUMP_INTR",
    "NLM_F_DUMP_FILTERED",
    "NLM_F_ROOT",
    "NLM_F_MATCH",
    "NLM_F_ATOMIC",
    "NLM_F_DUMP",
    "NLM_F_REPLACE",
    "NLM_F_EXCL",
    "NLM_F_CREATE",
    "NLM_F_APPEND",
    "NLM_F_CAPPED",
    "NLM_F_ACK_TLVS",
    "NLMSG_NOOP",
    "NLMSG_ERROR",
    "NLMSG_DONE",
    "NLMSG_OVERRUN",
    "NLMSG_CONTROL",
    "NLMSG_TRANSPORT",
    "NLMSG_MIN_TYPE",
    "NLMSG_MAX_LEN",
    "NLMSG_HDR_FORMAT",
    "NLMSG_HDR_SIZE",
    "SOL_NETLINK",
    "NETLINK_ADD_MEMBERSHIP",
    "NETLINK_DROP_MEMBERSHIP",
    "NETLINK_PKTINFO",
    "NETLINK_BROADCAST_ERROR",
    "NETLINK_NO_ENOBUFS",
    "NETLINK_RX_RING",
    "NETLINK_TX_RING",
    "NETLINK_LISTEN_ALL_NSID",
    "NETLINK_EXT_ACK",
    "NETLINK_GET_STRICT_CHK",
    "NLMSG_ALIGNTO",
    "RTM_BASE",
    "RTM_NEWLINK",
    "RTM_DELLINK",
    "RTM_GETLINK",
    "RTM_SETLINK",
    "RTM_NEWADDR",
    "RTM_DELADDR",
    "RTM_GETADDR",
    "RTM_NEWROUTE",
    "RTM_DELROUTE",
    "RTM_GETROUTE",
    "RTM_NEWNEIGH",
    "RTM_DELNEIGH",
    "RTM_GETNEIGH",
    "RTM_NEWRULE",
    "RTM_DELRULE",
    "RTM_GETRULE",
    "RTM_NEWQDISC",
    "RTM_DELQDISC",
    "RTM_GETQDISC",
    "RTM_NEWTCLASS",
    "RTM_DELTCLASS",
    "RTM_GETTCLASS",
    "RTM_NEWTFILTER",
    "RTM_DELTFILTER",
    "RTM_GETTFILTER",
    "RTM_NEWACTION",
    "RTM_DELACTION",
    "RTM_GETACTION",
    "RTM_NEWPREFIX",
    "RTM_GETMULTICAST",
    "RTM_GETANYCAST",
    "RTM_NEWNEIGHTBL",
    "RTM_GETNEIGHTBL",
    "RTM_SETNEIGHTBL",
    "RTM_NEWNDUSEROPT",
    "RTM_NEWADDRLABEL",
    "RTM_DELADDRLABEL",
    "RTM_GETADDRLABEL",
    "RTM_GETDCB",
    "RTM_SETDCB",
    "__RTM_MAX",
    "RTM_MAX",
    "RTM_NR_MSGTYPES",
    "RTM_NR_FAMILIES",
    "RTA_ALIGNTO",
    "RTN_UNSPEC",
    "RTN_UNICAST",
    "RTN_LOCAL",
    "RTN_BROADCAST",
    "RTN_ANYCAST",
    "RTN_MULTICAST",
    "RTN_BLACKHOLE",
    "RTN_UNREACHABLE",
    "RTN_PROHIBIT",
    "RTN_THROW",
    "RTN_NAT",
    "RTN_XRESOLVE",
    "__RTN_MAX",
    "RTN_MAX",
    "RTPROT_UNSPEC",
    "RTPROT_REDIRECT",
    "RTPROT_KERNEL",
    "RTPROT_BOOT",
    "RTPROT_STATIC",
    "RTPROT_GATED",
    "RTPROT_RA",
    "RTPROT_MRT",
    "RTPROT_ZEBRA",
    "RTPROT_BIRD",
    "RTPROT_DNROUTED",
    "RTPROT_XORP",
    "RTPROT_NTK",
    "RTPROT_DHCP",
    "RT_SCOPE_UNIVERSE",
    "RT_SCOPE_SITE",
    "RT_SCOPE_LINK",
    "RT_SCOPE_HOST",
    "RT_SCOPE_NOWHERE",
    "RTM_F_NOTIFY",
    "RTM_F_CLONED",
    "RTM_F_EQUALIZE",
    "RTM_F_PREFIX",
    "RT_TABLE_UNSPEC",
    "RT_TABLE_COMPAT",
    "RT_TABLE_DEFAULT",
    "RT_TABLE_MAIN",
    "RT_TABLE_LOCAL",
    "RT_TABLE_MAX",
    "RTA_UNSPEC",
    "RTA_DST",
    "RTA_SRC",
    "RTA_IIF",
    "RTA_OIF",
    "RTA_GATEWAY",
    "RTA_PRIORITY",
    "RTA_PREFSRC",
    "RTA_METRICS",
    "RTA_MULTIPATH",
    "RTA_PROTOINFO",
    "RTA_FLOW",
    "RTA_CACHEINFO",
    "RTA_SESSION",
    "RTA_MP_ALGO",
    "RTA_TABLE",
    "__RTA_MAX",
    "RTA_MAX",
    "RTNH_F_DEAD",
    "RTNH_F_PERVASIVE",
    "RTNH_F_ONLINK",
    "RTNH_ALIGNTO",
    "RTAX_UNSPEC",
    "RTAX_LOCK",
    "RTAX_MTU",
    "RTAX_WINDOW",
    "RTAX_RTT",
    "RTAX_RTTVAR",
    "RTAX_SSTHRESH",
    "RTAX_CWND",
    "RTAX_ADVMSS",
    "RTAX_REORDERING",
    "RTAX_HOPLIMIT",
    "RTAX_INITCWND",
    "RTAX_FEATURES",
    "RTAX_RTO_MIN",
    "__RTAX_MAX",
    "RTAX_MAX",
    "RTAX_FEATURE_ECN",
    "RTAX_FEATURE_SACK",
    "RTAX_FEATURE_TIMESTAMP",
    "RTAX_FEATURE_ALLFRAG",
    "PREFIX_UNSPEC",
    "PREFIX_ADDRESS",
    "PREFIX_CACHEINFO",
    "__PREFIX_MAX",
    "PREFIX_MAX",
    "TCA_UNSPEC",
    "TCA_KIND",
    "TCA_OPTIONS",
    "TCA_STATS",
    "TCA_XSTATS",
    "TCA_RATE",
    "TCA_FCNT",
    "TCA_STATS2",
    "TCA_STAB",
    "__TCA_MAX",
    "TCA_MAX",
    "NDUSEROPT_UNSPEC",
    "NDUSEROPT_SRCADDR",
    "__NDUSEROPT_MAX",
    "NDUSEROPT_MAX",
    "RTMGRP_LINK",
    "RTMGRP_NOTIFY",
    "RTMGRP_NEIGH",
    "RTMGRP_TC",
    "RTMGRP_IPV4_IFADDR",
    "RTMGRP_IPV4_MROUTE",
    "RTMGRP_IPV4_ROUTE",
    "RTMGRP_IPV4_RULE",
    "RTMGRP_IPV6_IFADDR",
    "RTMGRP_IPV6_MROUTE",
    "RTMGRP_IPV6_ROUTE",
    "RTMGRP_IPV6_IFINFO",
    "RTMGRP_IPV6_PREFIX",
    "RTNLGRP_NONE",
    "RTNLGRP_LINK",
    "RTNLGRP_NOTIFY",
    "RTNLGRP_NEIGH",
    "RTNLGRP_TC",
    "RTNLGRP_IPV4_IFADDR",
    "RTNLGRP_IPV4_MROUTE",
    "RTNLGRP_IPV4_ROUTE",
    "RTNLGRP_IPV4_RULE",
    "RTNLGRP_IPV6_IFADDR",
    "RTNLGRP_IPV6_MROUTE",
    "RTNLGRP_IPV6_ROUTE",
    "RTNLGRP_IPV6_IFINFO",
    "RTNLGRP_IPV6_PREFIX",
    "RTNLGRP_IPV6_RULE",
    "RTNLGRP_ND_USEROPT",
    "RTNLGRP_PHONET_IFADDR",
    "RTNLGRP_PHONET_ROUTE",
    "__RTNLGRP_MAX",
    "RTNLGRP_MAX",
    "NLMSG_ALIGN",
    "NLMSG_LENGTH",
    "NLMSG_SPACE",
    "set_pyritex_log_level",
]
